# Generated by Django 4.2.6 on 2023-10-26 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_remove_task_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
    ]
